questions = [
    {"id": 0, "question": "A liberdade dos negócios é a melhor maneira prática para uma sociedade prosperar", "effects": {"right": 1}},
    {"id": 1, "question": "A caridade é uma forma melhor de ajudar os necessitados do que o bem-estar social", "effects": {"right": 1}},
    {"id": 2, "question": "Os salários são sempre justos, pois os empregadores sabem melhor quanto vale o trabalho de um trabalhador", "effects": {"right": 1}},
    {"id": 3, "question": "É da 'natureza humana' ser ganancioso", "effects": {"right": 1}},
    {"id": 4, "question": "'Exploração' é um termo ultrapassado, pois as lutas do capitalismo do século XIX não existem mais", "effects": {"right": 1}},
    {"id": 5, "question": "O comunismo é um ideal que nunca pode funcionar na prática", "effects": {"right": 1}},
    {"id": 6, "question": "A tributação dos ricos é uma má idéia, a sociedade ficaria melhor sem ela", "effects": {"right": 1}},
    {"id": 7, "question": "Quanto mais você trabalha, mais você progride na escada social", "effects": {"right": 1}},
    {"id": 8, "question": "Organizações e corporações não podem ser confiáveis e precisam de regulamentação por parte do governo", "effects": {"right": -1}},
    {"id": 9, "question": "Um governo que prevê para todos é uma idéia inerentemente boa", "effects": {"right": -1}},
    {"id": 10, "question": "O atual sistema de bem-estar deveria ser expandido para combater ainda mais a desigualdade", "effects": {"right": -1}},
    {"id": 11, "question": "A terra não deve ser uma mercadoria a ser comprada e vendida", "effects": {"right": -1}},
    {"id": 12, "question": "Toda a indústria e o banco devem ser nacionalizados", "effects": {"right": -1}},
    {"id": 13, "question": "A classe é a divisão primária da sociedade", "effects": {"right": -1}},
    {"id": 14, "question": "A desigualdade econômica é muito alta no mundo", "effects": {"right": -1}},
    {"id": 15, "question": "Às vezes é correto que o governo possa espionar seus cidadãos para combater extremistas e terroristas", "effects": {"auth": 1}},
    {"id": 16, "question": "Números de autoridade, se moralmente corretos, são uma coisa boa para a sociedade", "effects": {"auth": 1}},
    {"id": 17, "question": "A força é necessária para que qualquer governo tenha sucesso", "effects": {"auth": 1}},
    {"id": 18, "question": "Somente o governo pode regular as organizações de forma justa e eficaz", "effects": {"auth": 1}},
    {"id": 19, "question": "A sociedade requer estrutura e burocracia para funcionar", "effects": {"auth": 1}},
    {"id": 20, "question": "IDs obrigatórios devem ser usados para garantir a segurança pública", "effects": {"auth": 1}},
    {"id": 21, "question": "Em tempos de crise, a segurança torna-se mais importante do que as liberdades civis", "effects": {"auth": 1}},
    {"id": 22, "question": "Se você não tem nada a esconder, não tem nada a temer", "effects": {"auth": 1}},
    {"id": 23, "question": "O governo deveria estar menos envolvido na vida cotidiana de seus cidadãos", "effects": {"auth": -1}},
    {"id": 24, "question": "Sem democracia, uma sociedade não é nada", "effects": {"auth": -1}},
    {"id": 25, "question": "A anulação pelo júri deve ser legal", "effects": {"auth": -1}},
    {"id": 26, "question": "Quanto menor o governo, mais livre o povo", "effects": {"auth": -1}},
    {"id": 27, "question": "O governo deve, no máximo, fornecer serviços de emergência e aplicação da lei", "effects": {"auth": -1}},
    {"id": 28, "question": "A polícia não foi feita para proteger o povo, mas para manter o status quo pela força", "effects": {"auth": -1}},
    {"id": 29, "question": "As escolas estatais são uma má idéia porque nosso estado não deveria estar influenciando nossas crianças", "effects": {"auth": -1}},
    {"id": 30, "question": "Dois indivíduos que consentem devem ser capazes de fazer o que quiserem um com o outro, mesmo que isso me deixe desconfortável", "effects": {"prog": 1}},
    {"id": 31, "question": "O corpo de um indivíduo é sua própria propriedade, e ele deve ser capaz de fazer tudo o que desejar", "effects": {"prog": 1}},
    {"id": 32, "question": "Uma pessoa deve ser capaz de adorar quem quer ou o que quiser", "effects": {"prog": 1}},
    {"id": 33, "question": "O nudismo é perfeitamente natural", "effects": {"prog": 1}},
    {"id": 34, "question": "Os animais merecem certos rights universais", "effects": {"prog": 1}},
    {"id": 35, "question": "O gênero é uma construção social, não um estado natural de coisas", "effects": {"prog": 1}},
    {"id": 36, "question": "As leis baseadas em valores culturais, ao invés de valores éticos, não são justiça", "effects": {"prog": 1}},
    {"id": 37, "question": "A autonomia do corpo se estende até aos menores, aos doentes mentais e aos criminosos graves", "effects": {"prog": 1}},
    {"id": 38, "question": "A homossexualidade é contra os meus valores", "effects": {"prog": -1}},
    {"id": 39, "question": "Os indivíduos transexuais não devem ser capazes de adotar crianças", "effects": {"prog": -1}},
    {"id": 40, "question": "As drogas são prejudiciais e devem ser proibidas", "effects": {"prog": -1}},
    {"id": 41, "question": "A pena de morte deve existir para certos crimes", "effects": {"prog": -1}},
    {"id": 42, "question": "Crimes sem vítimas ainda devem ser punidos", "effects": {"prog": -1}},
    {"id": 43, "question": "Não se pode ser moral sem religião", "effects": {"prog": -1}},
    {"id": 44, "question": "Os pais devem ter poder absoluto sobre seus filhos, pois eles são mais velhos e mais experientes", "effects": {"prog": -1}},
    {"id": 45, "question": "Multiculturalismo é ruim", "effects": {"prog": -1}}
];